/// @description Insert description here
// You can write your code in this editor


// Inherit the parent event
event_inherited();

// adding dialogue (so people say stuff)
dialogue.add(spr_chara_example_1, "PARSELY\n\nHello!");
dialogue.add(spr_chara_example_2, "CHARAN\n\nI exist too");
dialogue.add(spr_chara_example_1, "PARSELY\n\nThis is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test this is a test");
dialogue.add(spr_blank, "This is system text.");
dialogue.add(spr_blank, "And this is\n\to check something about dialogue height");
dialogue.add(spr_blank, "This is system text to test the system. This is system text to test the system. This is system text to test the system. This is system text to test the system. This is system text to test the system. This is system text to test the system. This is system text to test the system. This is system text to test the system. This is system text to test the system. This is system text to test the system. This is system text to test the system. This is system text to test the system. This is system text to test the system. This is system text to test the system. This is system text to test the system.This is system text to test the system.");

